# Generated by Django 4.2.3 on 2023-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username_user_github_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openai_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
