# Generated by Django 4.2.5 on 2023-10-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Session', max_length=200)),
                ('memory', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('repo_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hostOnGithub', models.BooleanField(default=False)),
                ('specifications', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published')], default='GENERATING', max_length=20)),
                ('htmlContent', models.TextField()),
                ('jsContent', models.TextField()),
                ('cssContent', models.TextField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='llm.session')),
            ],
            options={
                'verbose_name': 'Webpage',
                'verbose_name_plural': 'Webpages',
            },
        ),
    ]
