# Generated by Django 4.2.3 on 2023-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='memory',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
