# Generated by Django 4.2.3 on 2023-08-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_session_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='hostOnGithub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webpage',
            name='state',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published')], default='INITIAL', max_length=20),
        ),
    ]
