# Generated by Django 4.2.3 on 2023-08-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_webpage_hostongithub_webpage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='repo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
