# Generated by Django 4.2.3 on 2023-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_alter_webpage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='state',
            field=models.CharField(choices=[('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published')], default='GENERATING', max_length=20),
        ),
    ]
